---

- name: plugins | Get data
  ansible.builtin.set_fact:
    _plugin_data: "{{ _plugin_data + (bareos_fd_plugin_list | selectattr('name', 'equalto', item) | list) }}"  # noqa: jinja[invalid] yaml[line-length]
  loop: "{{ bareos_fd_plugins }}"
  vars:
    _plugin_data: []  # empty list to append to

- name: plugins | Install Bareos plugin packages
  ansible.builtin.package:
    name: "{{ item.packages }}"
    state: present
  loop: "{{ _plugin_data }}"
  notify:
    - Check configuration
    - Restart bareos-filedaemon
  ignore_errors: "{{ ansible_check_mode }}"

# while not an actual plugin, still treat PSQL running in Docker with the same logic
- name: plugins | Deploy PostgreSQL Docker backup script
  ansible.builtin.template:
    src: templates/bareos-psql-docker-dump.sh.j2
    dest: "/usr/local/bin/bareos-psql-docker-dump.sh"
    owner: root
    group: root
    mode: "0751"
  when:
    - '"postgresql_docker" in bareos_fd_plugins'
