---
# defaults file for bareos_fd

# The client has these configuration parameters.

# Backup existing configurations.
bareos_fd_backup_configurations: false

# Install debug packages. This requires the debug repositories to be enabled.
bareos_fd_install_debug_packages: false

# The hostname of the File Daemon.
bareos_fd_hostname: "{{ inventory_hostname }}"

# The maximum bandwidth to use.
bareos_fd_max_job_bandwidth: "10 mb/s"

# The message to use.
bareos_fd_message: "Standard"

# The maximum number of concurrent jobs.
bareos_fd_maximum_concurrent_jobs: 20

# Enable TLS.
bareos_fd_tls_enable: true

# Verify the peer.
bareos_fd_tls_verify_peer: false

# The inteval in seconds to send a heartbeat.
bareos_fd_heartbeat_interval: 0

# The Directors to connect to.
bareos_fd_directors:
  - name: "bareos-dir"
    password: "secretpassword"
    monitor: no
    description: "Allow the configured Director to access this file daemon."
  - name: bareos-mon
    password: "secretpassword"
    monitor: yes
    description: "Restricted Director, used by tray-monitor to get the status of this file daemon."

# The Messages to configure.
bareos_fd_messages:
  - name: "Standard"
    director:
      server: bareos-dir
      messages:
        - all
        - "!skipped"
        - "!restored"
    description: "Send relevant messages to the Director."

# For encryption of data, set this to `true`.
bareos_fd_encryption_enable: false

# You may bring your own private key. If not specified, a new one will be generated.
bareos_fd_encryption_private_key: ""

# The master public key to use.
bareos_fd_encryption_master_public_key: ""

# Enable bareos-fd nice settings
bareos_fd_io_nice_enable: false

# Niceness value between -20 (highest priority) to 20 (least priority)
bareos_fd_io_nice_value: 10

# I/O scheduling class: realtime, best-effort or idle
bareos_fd_io_scheduling_class: best-effort

# I/O scheduling priority between 0 (highest priority) and 7 (lowest priority)
bareos_fd_io_scheduling_priority: 7

# Backup excludes on the client, which will be placed as files for all paths in bareos_fd_nobackup_excludes
bareos_fd_nobackup_filename: .nobackup  # recommendation according to bareos
bareos_fd_nobackup_excludes: []

##
# Setup Relax-and-Recover (ReaR) on client
# #

bareos_fd_rear_enable: false
bareos_fd_rear_client: "{{ inventory_hostname }}"
bareos_fd_rear_fileset: LinuxAll
bareos_fd_rear_restore_job: RestoreFiles
bareos_fd_rear_console_name: "rear-{{ inventory_hostname_short }}-console"
bareos_fd_rear_console_pass: "{{ lookup('ansible.builtin.password', '/dev/null', seed=inventory_hostname, length=20, chars='ascii_letters') }}"

##
# Defaults used by the Bareos PostgreSQL backup plugin
##

# PostgreSQL major version
# This value will be overwritten on Debian based distros by the actual version in-use.
# On Red Hat based distros, the value is not required as of now.
bareos_fd_plugin_psql_version: 15

# Bareos does not cleanup the PostgreSQL WAL archive files on its own, which can lead
# If you want to . This is disabled per default to avoid accidential file loss.
bareos_fd_plugin_psql_wal_cleanup_enable: false
bareos_fd_plugin_psql_wal_cleanup_max_age: 14

# during the day to avoid potential overlap with backup process
bareos_fd_plugin_psql_wal_cleanup_schedule: "*-*-* 14:00:00"
