---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-bareos_fd
      bareos_fd_backup_configurations: true
      bareos_fd_install_debug_packages: true
      bareos_fd_encryption_enabled: true
      bareos_fd_encryption_private_key: |
        -----BEGIN PRIVATE KEY-----
        MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALnT/+JXRTeg0fgk
        ef0y3tNGhN45rKoioNi40XVd7OOWzknHIf6Dz7js1c7RxPUJ4hOITZCWjBVQKzQe
        MeFr8PUltqxNY7W3JFz4/QlIgF4/hvi8rTFAi2djHsOdNFEk31mh+K6G6LGfchuc
        kCG3b86xZGDWaWafnyQicqqHOttjAgMBAAECgYAbZXPuLKuZve32xXnuqFdNkrH4
        CUy5cI2CJg1LXmOUUiFrox4R5eD0BIapDSgacDCSbJ/y1x8j7UPRVTpJX56QZUD/
        FByRAPc5+/nPuiltB9sSNmFx3FlTeF4N0oyglEioz3zM5ilUYkdVetj+vYnQJKkt
        LGysJ46ZO7pBdmjsgQJBAO7e3Dj8umZfS9EC3Xr/ykxFKSSSUenFg6qNu1lADCUo
        S9iJu5BY0R81ab7uWdgBPUHtW1vp/WhpnfoPMs80dOECQQDHJ2WJyXZtHSqBzXRZ
        J/+Ki0E4uuYuJn9CCb2w5Fegq1BW+6FU0759s3RJCEbFt3B2Xy4G+y7QOjglb0DN
        bFTDAkBQxshN9RjLmZo32fIvr+QnGpQpK9nLZeF6gWdDbScuQYw0c48b5w0Asr1J
        taxoITMn4i4szNnGv0CO2SjjbOfBAkAQEO6REg6auNqgBBoZwy9LVvaZBALjwDlN
        84k5BwLGtGtTyRL3y+k3LM35wlArTSQmeIE3EPZy1++FnZcFu3KPAkEAtIZOonLt
        EtRs4axJi3vnPnPCje92Usdd3QOCCJHt4zA5GITp866aiO0bW5lLc7ZzUNEUk3jt
        ICo3CGGSXV7yiA==
        -----END PRIVATE KEY-----
      bareos_fd_encryption_master_public_key: |
        -----BEGIN CERTIFICATE-----
        MIICSjCCAbOgAwIBAgIUd8WfhMKbB1MSc47VEsokPgViZKIwDQYJKoZIhvcNAQEL
        BQAwNzELMAkGA1UEBhMCQ0gxEzARBgNVBAgMClNvbWUtU3RhdGUxEzARBgNVBAoM
        CkFkZmluaXMgQUcwHhcNMjQwNTEzMTIwMDMwWhcNMjQwNjEyMTIwMDMwWjA3MQsw
        CQYDVQQGEwJDSDETMBEGA1UECAwKU29tZS1TdGF0ZTETMBEGA1UECgwKQWRmaW5p
        cyBBRzCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAudP/4ldFN6DR+CR5/TLe
        00aE3jmsqiKg2LjRdV3s45bOScch/oPPuOzVztHE9QniE4hNkJaMFVArNB4x4Wvw
        9SW2rE1jtbckXPj9CUiAXj+G+LytMUCLZ2Mew500USTfWaH4robosZ9yG5yQIbdv
        zrFkYNZpZp+fJCJyqoc622MCAwEAAaNTMFEwHQYDVR0OBBYEFK/HMqCU8j2Dqj0R
        /c2Xrl/MGaq8MB8GA1UdIwQYMBaAFK/HMqCU8j2Dqj0R/c2Xrl/MGaq8MA8GA1Ud
        EwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADgYEAUO7icu1fG+mXUfJoMEpdhGCr
        Zn0Ll4hplw9eANrGYnbC2FIWdh7tj23dFhm/kb0YRqI2arpPyYYagmu7eK89/22g
        wyrW5xc17ivohUS+sN8lPqrKcXrRBveQ0FnvUbkjEmtmgHSYgjdCxoGMIcqpn8BC
        m/1hu95J5z6/IZEm7oM=
        -----END CERTIFICATE-----
      bareos_fd_directors:
        - name: "bareos-dir"
          password: "secretpassword"
          monitor: false
          connection_from_client_to_director: true
          connection_from_director_to_client: false
          tls_enable: true
          tls_verify_peer: false
        - name: "disabled-director"
          enabled: false
      bareos_fd_messages:
        - name: "Standard"
          director:
            server: bareos-dir
            messages:
              - all
              - "!skipped"
              - "!restored"
          description: "Send relevant messages to the Director."
          append:
            file: "/var/log/bareos/bareos.log"
            messages:
              - all
              - "!skipped"
              - "!terminate"
          console:
            - all
            - "!skipped"
            - "!saved"
        - name: "disabled-message"
          enabled: false
      bareos_fd_plugins:
        - mariabackup
        - mysql
        - mysql_xtrabackup
        # TODO disabled as package `bareos-filedaemon-ldap-python-plugin`
        # has broken dependencies on Debian (python-ldap instead of python3-ldap)
        #  - ldap
