---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  roles:
    #- role: robertdebock.bootstrap
    - role: adfinis.bareos_repository
      bareos_repository_enable_tracebacks: true

  pre_tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name: gpg
        state: present
