---
- name: Prepare
  hosts: all
  # has to be false to avoid become issues on RHEL container images
  become: false
  gather_facts: true

  roles:
    - role: robertdebock.bootstrap
    - role: adfinis.bareos_repository
      bareos_repository_enable_tracebacks: true
