---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    bareos_fd_nobackup_filename: .nomoleculebackup
    bareos_fd_nobackup_excludes:
      - /home
      - /root
      - /var/lib

  tasks:
    - name: Check if port 9102 is listening
      ansible.builtin.wait_for:
        port: 9102

    - name: Test configuration for warnings
      ansible.builtin.command:
        cmd: bareos-fd --test-config
      become_user: bareos
      register: bareos_fd_test_config
      failed_when:
        - bareos_fd_test_config.stdout_lines is search("There are configuration warnings")

    # have to be specified in converge.yml: `bareos_fd_plugins`
    - name: Check if plugin packages were installed
      ansible.builtin.package:
        name:
          - bareos-filedaemon-mariabackup-python-plugin
          - bareos-filedaemon-percona-xtrabackup-python-plugin
          - bareos-filedaemon-ldap-python-plugin
        state: present
      check_mode: true
      diff: true
      register: _result
      failed_when: _result.changed
      when:
        - ansible_facts.os_family != "Archlinux"  # not supported for FD Plugins

    - name: plugins_mariadb | Get /root/.my.cnf stats
      ansible.builtin.stat:
        path: /root/.my.cnf
      register: _my_cnf

    - name: plugins_mariadb | Verify /root/.my.cnf exists
      ansible.builtin.assert:
        that:
          - _my_cnf.stat.exists
          - _my_cnf.stat.pw_name == "root"  # owner
          - _my_cnf.stat.gr_name == "root"

    - name: Get nobackup file stats
      ansible.builtin.stat:
        path: "{{ item }}/{{ bareos_fd_nobackup_filename }}"
      loop: "{{ bareos_fd_nobackup_excludes }}"
      register: _nobackup_files

    - name: Verify nobackup files exist
      ansible.builtin.assert:
        that:
          - item.stat.exists
          - item.stat.pw_name == "bareos"
          - item.stat.gr_name == "bareos"
      loop: "{{ _nobackup_files.results }}"
