---

dependency:
  name: galaxy
  options:
    role-file: molecule/postgresql/requirements.yml
    requirements-file: molecule/postgresql/requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: "bareosfd-${image:-fedora40}${TOX_ENVNAME}"
    image: "geerlingguy/docker-${image:-fedora40}-ansible:latest"
    command: "/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    systemd: true
provisioner:
  name: ansible
verifier:
  name: ansible
