---

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '3 2 2 * *'

jobs:

  test:
    uses: adfinis/github-workflows-bareos/.github/workflows/molecule.yaml@eedff15b52be3c117bd5f7a28492494596399311 # v0.8.0

  test_postgresql:
    runs-on: ubuntu-22.04  # ubuntu latest will for all RHEL-based distros: https://github.com/rocky-linux/sig-cloud-instance-images/issues/56
    container:
      image: python:3.9
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "debian12"
          - image: "debian13"
          - image: "fedora43"
          - image: "ubuntu2204"
          - image: "ubuntu2404"
          - image: "ubuntu2604"
          - image: "rockylinux9"
          - image: "rockylinux10"
    steps:
      - name: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          path: "${{ github.repository }}"

      - name: molecule postgresql plugin scenario
        uses: gofrolist/molecule-action@4fd2c291c3faa2a9f3f95fbbad9e4c20988433b5 # v2.9.2
        with:
          molecule_command: test
          molecule_args: "--scenario-name postgresql"
        env:
          image: ${{ matrix.config.image }}
